# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'

url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
gems: [jekyll-paginate]
paginate_path: "page:num"

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
